### ISSUE TITLE
Error occured when trying to start the application.

### ISSUE THREAD

**Issue by srikarsashankbandi** [SoftCreatR/dataloader-for-linux#1]
Hi Sascha Greuel,

Nice work on creating debian repo for salesforce dataloader.
I have installed your stable apex dataloader package in ubuntu 22.04 after installing all your prerequisites java runtime and maven, When I tried to start the installed application I have encountered this error message " error creating output directory:/opt/dataloader/configs ".
please tell me where did it went wrong?

Thankyou
srikar sashank bandi.
![Screenshot from 2022-06-08 12-05-05](https://user-images.githubusercontent.com/10140923/172548264-f613a6bf-bbc2-4486-b31d-9ac6fca38cc9.png)

**Comment by SoftCreatR** [comment]
Hi,

I have to admit, that I didn't test it on Debian, but on Ubuntu. The error message is produced here:

https://github.com/forcedotcom/dataloader/blob/498fbc8247950b484c5b84a8e0871e333ec0876c/src/main/java/com/salesforce/dataloader/controller/Controller.java#L367-L373

Did you try running it with `sudo`? I could imagine, that creating or modifying files within `/opt` requires higher privileges.

**Comment by srikarsashankbandi** [comment]
Sascha, I have tried root install as well using sudo. still receiving same error.

**Comment by SoftCreatR** [comment]
Try creating the directory by hand then:

`sudo mkdir -p /opt/dataloader/configs`

**Comment by srikarsashankbandi** [comment]
![Screenshot from 2022-06-08 12-24-24](https://user-images.githubusercontent.com/10140923/172551533-ab07de23-30c6-47df-bd3e-6f8ffc9f5d2d.png)

**Comment by srikarsashankbandi** [comment]
> Try creating the directory by hand then:
> 
> `sudo mkdir -p /opt/dataloader/configs`

![Screenshot from 2022-06-08 12-29-56](https://user-images.githubusercontent.com/10140923/172552452-8a83ebd8-8483-467f-b893-4cb68d80d5f6.png)

**Comment by SoftCreatR** [comment]
I'll check that in my WSL installation.

**Comment by SoftCreatR** [comment]
I tried it on a fresh Debian (bullseye) machine, and it works fine so far:

$ sudo apt install default-jdk
$ sudo dpkg -i apex-dataloader-55.0.1-1653500767-fea00a4.deb
$ sudo dataloader

However, I can't test the GUI, but creating the `configs` directory, and the configuration files works as expected:

![image](https://user-images.githubusercontent.com/81188/172557545-2f35281d-fc7d-42fa-9016-e31cad44d317.png)

**Comment by srikarsashankbandi** [comment]
> I tried it on a fresh Debian (bullseye) machine, and it works fine so far:
> 
> ```shell
> sudo apt install wget default-jdk libswt-gtk-4-java
> ```
> 
> ```shell
> wget https://t.ly/2nGKh -O dataloader.deb
> ```
> 
> ```shell
> sudo dpkg -i apex-dataloader-55.0.1-1653500767-fea00a4.deb
> ```
> 
> ```shell
> sudo dataloader
> ```
> 
> Creating the `configs` directory, and the configuration files works as expected:
> 
> ![image](https://user-images.githubusercontent.com/81188/172558639-37c3156a-f3c0-4c4f-a227-1222de14e8ad.png)

Hooray. Let me try your steps on ubuntu 22.04 and see weather it works.

**Comment by srikarsashankbandi** [comment]
Sascha, It worked perfectly .Thank you so  much for your help . I love your work in creating this repo for dataloder.

**Comment by SoftCreatR** [comment]
I've corrected the commands above 😄
